---
title: "Kupa"
format: html   
---

```{r import}
# load data and packages

library(tidyverse)
library(tidytuesdayR)
library(dplyr)
library(forcats)
library(DataExplorer)

tuesdata <- tidytuesdayR::tt_load(2021, week = 29)

scoobydoo <- tuesdata$scoobydoo
```


```{r}
scoob_wrangles <- Scoob |> 
  select(series.name, title, monster.name, monster.gender, captured.fred, captured.daphnie, captured.scooby, captured.velma, captured.shaggy, culprit.name, culprit.gender)
```

```{r}
#individual monsters of tv series 
scoobydoo_clean <- Scoob |>
  filter(season %in% c("1", "2","3", "4"),
         format == "TV Series") |>
  filter(monster.name != "NULL") |>
  mutate(monster.name = str_replace(monster.name, "Dr. Phineus Phibes,Agent 1,Agent 2,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent,8,Agent,9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal", "Dr. Phineus Phibes,Agent 1,Agent 2,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent 8,Agent 9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal")) |>
  select(title, season, series.name, contains("monster")) |>
  pivot_longer(cols = c(monster.name, monster.gender, monster.type, monster.subtype, monster.species), names_to = "monster_var", values_to = "monster") |>
  separate(monster, c("1monster", "2monster", "3monster", "4monster", "5monster", "6monster", "7monster", "8monster", "9monster", "10monster", "11monster", "12monster", "13monster", "14monster", "15monster"), sep = ",") |>
  pivot_longer(cols = ends_with("monster"), names_to = "monster_num", values_to = "monster_value") |>
  pivot_wider(names_from = monster_var, values_from = monster_value) |>
  mutate(monster_num = as.numeric(str_sub(monster_num, 1, 1))) |>
  na.omit()


```













