---
title: "Report"
execute: 
  echo: true      # change to true to show the code
code-fold: false  # change to true to fold the code chunks
  
---

Your report will go here.

```{r}
# load data and packages

library(tidyverse)
library(tidytuesdayR)
library(patchwork)

tuesdata <- tidytuesdayR::tt_load(2021, week = 29)

scoobydoo <- tuesdata$scoobydoo
```

```{r}
# wrangling data


# wrangle/clean monster data 
scoobydoo_monsters <- scoobydoo |>
  filter(season %in% c("1", "2","3", "4"),
         format == "TV Series") |>
  filter(monster_name != "NULL") |>
  mutate(unmasked = case_when(
    unmask_fred == TRUE | unmask_daphnie == TRUE | unmask_velma == TRUE | 
    unmask_shaggy == TRUE | unmask_scooby == TRUE | unmask_other == TRUE ~ "Yes", 
    TRUE ~ "No")) |>
  mutate(monster_amount = ifelse(title == "The Ghastly Ghost Town", 5, monster_amount),
         monster_amount = ifelse(title == "Me and My Shadow Demon", 3, monster_amount)) |>
  mutate(monster_name = str_replace(monster_name, "Dr. Phineus Phibes,Agent 1,Agent 2,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent,8,Agent,9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal", "Dr. Phineus Phibes,Agent 1,Agent 2,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent 8,Agent 9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal"),
         monster_name = str_replace(monster_name, "Dr. Phineus Phibes,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent,9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal,Misty Swiss", "Dr. Phineus Phibes,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent 9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal,Misty Swiss"),
         monster_name = str_replace(monster_name, "Dr. Phineus Phibes,Dr. Trebla,Agent 1,Agent 2,Mark,Ricky,Agent,4,Agent 7,Agent 11", "Dr. Phineus Phibes,Dr. Trebla,Agent 1,Agent 2,Mark,Ricky,Agent 4,Agent 7,Agent 11")) |>
  select(title, season, series_name, contains("monster"), unmasked) |>
  pivot_longer(cols = c(monster_name, monster_gender, monster_type, monster_subtype, monster_species), names_to = "monster_var", values_to = "monster") |>
  separate(monster, c("1monster", "2monster", "3monster", "4monster", "5monster", "6monster", "7monster", "8monster", "9monster", "10monster", "11monster", "12monster", "13monster", "14monster", "15monster"), sep = ",") |>
  pivot_longer(cols = ends_with("monster"), names_to = "monster_num", values_to = "monster_value") |>
  pivot_wider(names_from = monster_var, values_from = monster_value) |>
  separate(monster_num, c("monster_num", "x"), sep = "m") |>
  mutate(monster_num = as.numeric(monster_num)) |>
  select(-x) |>
  na.omit() |>
  mutate(monster_type = ifelse(monster_type == "Disugised", "Disguised", monster_type),
          monster_type = ifelse(monster_type == "Disguise", "Disguised", monster_type)) |>
  mutate(monster_type = str_trim(monster_type, side = "left"))



# wrangle/clean culprit data
scoobydoo_culprits <- scoobydoo |>
  filter(season %in% c("1", "2","3", "4"),
         format == "TV Series") |>
  filter(culprit_name != "NULL") |>
  select(title, season, series_name, motive, contains("culprit")) |>
  pivot_longer(cols = c(culprit_name, culprit_gender), names_to = "culprit_var",
               values_to = "culprit") |>
  separate(culprit, c("1culprit", "2culprit", "3culprit", "4culprit", "5culprit",
                      "6culprit", "7culprit", "8culprit", "9culprit", "10culprit",
                      "11culprit"), sep = ",") |>
  pivot_longer(cols = ends_with("culprit"), names_to = "culprit_num", values_to = "culprit_value") |>
  pivot_wider(names_from = culprit_var, values_from = culprit_value) |>
  separate(culprit_num, c("culprit_num", "x"), sep = "c") |>
  select(-x) |>
  mutate(culprit_num = as.numeric(culprit_num)) |>
  na.omit() |>
  mutate(culprit_gender = str_trim(culprit_gender, side = "left"))
```
# Motivation

# Research Question

# Background

# Data
* We are only focusing on Scooby-Doo episodes from TV series (excluding movies or special cross-over episodes)  


# Data Insights
## Exploration of Monster Genders
```{r}
# graph of male vs female monsters
```


```{r}
# monster genders (%) by series
scoobydoo_monsters |>
  group_by(monster_gender) |>
  mutate(n = n()) |>
  ggplot(aes(y = series_name, fill = monster_gender)) +
  geom_bar(position = "fill")+
  labs(x = "Percent", y = "Series Name",
       title = "% of Monsters by Gender per Series",
       fill = "Monster Gender",
       caption = "Data collected by @plummye on Kaggle, week 07/13/2021 on TidyTuesday")
```

```{r}
#uses scoodydoo_clean data which is not in the qmd


#| fig-cap: "Data source: Jon Harmon, @jonthegeek on Kaggle. Accessed on 04/09/2025. https://github.com/rfordatascience/tidytuesday/blob/main/data/2021/2021-07-13/readme.md." 
#| fig-alt: "This is a bar chart of monster type by gender. On the y-axis, there are all the monster types. On the x-axis, are decimals counting up to 1. The bars show the proportion of each monster that is male, female, and none. The monster type with most female versions is magician. More than half magicians are female. After that, not many monsters have female versions – undead, ancient, mythical, mechanical have a few female versions, but less than a quarter of those monsters are female. "
ggplot(scoobydoo_clean, aes(y = monster_type, fill = monster_gender,)) + 
  geom_bar(position = "fill")+
  labs(x = "Proportion of Each Gender", y = "Monster Type", title = "Monster Type by Gender",  fill = "Monster Gender") +
  scale_fill_viridis_d() 
```

## Female Monsters over Time
```{r}
# code/graph tba
```

## Portrayal of Male vs Female Monsters
```{r}
# female monsters often portrayed as magicians, specifically witches

p1<- scoobydoo_monsters |> 
  filter(monster_type == "Magician") |>
  ggplot(aes(y=monster_subtype, fill = monster_gender))+
  geom_bar()+
  labs(title = "Subtypes of Magician Monsters, by Gender",
       x = "Count", y = "Monster Subtype",
       fill = "Monster Gender") +  
       scale_fill_viridis_d()   

p2 <- scoobydoo_monsters |>
  filter(monster_subtype %in% c("Witch", "Wizard")) |>
  ggplot(aes(x=monster_subtype, fill = monster_gender))+
  geom_bar()+
  labs(title = "Witch and Wizard Monsters by Gender",
       x = "Monster Subtype", y = "Count",
       fill = "Monster Gender",
       caption = "Data collected by @plummye on Kaggle; TidyTuesday week of 07/13/2021")+
  facet_wrap(~monster_type) +  
       scale_fill_viridis_d()   

p1 / p2
```



## Culprit Motives
```{r}
# code/graph tba
```






# Conclusions

# Limitations and Future Work
