---
title: "Adele F"
---

**Perfecting Teamwork: Building High-Performing Teams by Encouraging Learning**

**By: Think Fast Talk Smart: Communication Techniques**

[**Link to Podcast:**]{.underline} <https://open.spotify.com/episode/7pHpUwOMGOC2FXcikLvySt?si=9336eeaebb7d416f>

[**Summary:**]{.underline}

I listened to an episode of the Think Fast Talk Smart podcast with guest Sarah Singer, a doctor and medical communication coordinator.
Her main requirements for a high-functioning and efficient team were that the group is team-oriented, learning-oriented, and system-oriented.
There need to be clear roles in a team and if there is a hierarchy, it needs to be weak and relatively level so that everyone can learn from each other in their areas of expertise.
In this vein, people also need to be willing to make mistakes in front of each other and learn from them, no matter their level of seniority in a team.
These ideas about hierarchy were very valid in a medical context but apply less to our teamwork in class.

Specifically, what I can summarize from this podcast that will help me in class teamwork is communication nuances.
One thing that helps a team work well according to the podcast is repeating back what a team member has said to make sure that it is enacted correctly and to help everyone feel heard.
This is especially important when learning new techniques and sharing new ideas with each other.
I also think that the idea of learning from our mistakes is something that we will be able to do very well and need to focus on in this project, rather than getting too frustrated and bogged down by feeling stuck.
